### ISSUE TITLE
Can not download boxes( centos7-standard.box and openstack.box ) in China

### ISSUE THREAD

**Issue by bopzjy** [ksingh7/ceph-cookbook#2]
I can't connect to www.dropbox.com in China. Can you provide available URLs? Thanks.

**Comment by ksingh7** [comment]
@bopzjy so looks like this is because of the big country firewall. Do you have any proxy access to outside world ?

**Comment by bopzjy** [comment]
@ksingh7 yeah,because of the "Great Wall",I got it. I will find proxy by myself. Thank you!
